export const metadata = {
  title: 'Privacy Policy',
  description: 'Privacy Policy for Indian Virtual — how we collect, use, and protect your personal data.',
  alternates: { canonical: 'https://indianvirtual.site/privacy' },
}

import { Box, Heading, Text, VStack, Flex } from '@chakra-ui/react'

const LAST_UPDATED = 'May 9, 2026'
const CONTACT = 'ceo@indianvirtual.site'
const SITE = 'https://indianvirtual.site'

function Section({ title, children }) {
  return (
    <Box mb={8}>
      <Heading as="h2" fontSize="15px" fontWeight="700" color="#111" mb={3} letterSpacing="-0.01em">
        {title}
      </Heading>
      <VStack align="stretch" gap={2.5}>
        {children}
      </VStack>
    </Box>
  )
}

function P({ children }) {
  return <Text fontSize="14px" color="#444" lineHeight="1.8">{children}</Text>
}

function Li({ children }) {
  return (
    <Flex gap={3} align="flex-start" pl={2}>
      <Text fontSize="14px" color="#999" mt="1px" flexShrink={0}>—</Text>
      <Text fontSize="14px" color="#444" lineHeight="1.8" flex={1}>{children}</Text>
    </Flex>
  )
}

function A({ href, children }) {
  return (
    <Text as="a" href={href} target="_blank" rel="noopener noreferrer"
      color="#2563eb" textDecoration="underline" textUnderlineOffset="3px"
      _hover={{ color: '#1d4ed8' }}>
      {children}
    </Text>
  )
}

function Strong({ children }) {
  return <Text as="span" fontWeight="600" color="#222">{children}</Text>
}

export default function PrivacyPage() {
  return (
    <Box bg="white" minH="100vh">
      <Box maxW="680px" mx="auto" px={{ base: 5, md: 8 }} pt={{ base: 14, md: 20 }} pb={24}>

        {/* Header */}
        <Box mb={10} pb={8} borderBottom="1px solid #e5e7eb">
          <Text fontSize="12px" fontWeight="600" color="#9ca3af" letterSpacing="0.1em" textTransform="uppercase" mb={3}>
            Indian Virtual · Legal
          </Text>
          <Heading as="h1" fontSize={{ base: '28px', md: '36px' }} fontWeight="800" color="#111" letterSpacing="-0.03em" lineHeight="1.15" mb={3}>
            Privacy Policy
          </Heading>
          <Text fontSize="13px" color="#9ca3af">Last updated: {LAST_UPDATED}</Text>
        </Box>

        {/* Intro */}
        <Box mb={10}>
          <P>
            Indian Virtual ("we", "us", "INVA") operates the Crew Center at{' '}
            <A href={`${SITE}/crew`}>{SITE}/crew</A> and the main website at{' '}
            <A href={SITE}>{SITE}</A>.
            This policy explains what personal data we collect when you use our platform, why we collect it,
            how we protect it, and what rights you have over it.
          </P>
        </Box>

        <Section title="1. Who We Are">
          <P>
            Indian Virtual is an informal virtual airline community built around the Infinite Flight
            simulation platform. We are not a registered legal entity. For all privacy-related matters,
            contact us at <A href={`mailto:${CONTACT}`}>{CONTACT}</A>.
          </P>
        </Section>

        <Section title="2. Data We Collect">
          <P><Strong>2.1 Account data via Discord OAuth</Strong></P>
          <P>
            We authenticate exclusively through Discord's OAuth 2.0 service. When you log in, Discord
            provides us with your Discord user ID, username, display name, avatar hash, and email address.
            We do not store your Discord password.
          </P>

          <P><Strong>2.2 Crew profile data</Strong></P>
          <Li>IFC (Infinite Flight Community) username — provided by you on registration</Li>
          <Li>Pilot rank and accumulated flight hours</Li>
          <Li>Permissions level (e.g. staff access)</Li>
          <Li>Last active timestamp</Li>

          <P><Strong>2.3 Flight records (PIREPs)</Strong></P>
          <Li>Flight number, date, and block time</Li>
          <Li>Departure and arrival ICAO codes</Li>
          <Li>Aircraft type, operator, and earnings multiplier</Li>
          <Li>Pilot and admin comments, approval status, and review timestamps</Li>

          <P><Strong>2.4 Contribution and payment data</Strong></P>
          <Li>IFC name and optional Discord ID associated with a contribution</Li>
          <Li>Contribution amount and target goal</Li>
          <Li>Manual UPI confirmation reference generated by our platform — we do not store card numbers, UPI handles, or bank account details</Li>
          <Li>Lotus Privé join date, monthly pledge status, and Discord avatar URL for the member showcase</Li>

          <P><Strong>2.5 Technical data</Strong></P>
          <Li>Session token stored in an HTTP-only cookie managed by NextAuth.js</Li>
          <Li>SimBrief OFP routing data tied to your dispatch (not personal data)</Li>
        </Section>

        <Section title="3. How We Use Your Data">
          <Li>To authenticate you and maintain your session</Li>
          <Li>To operate your pilot profile, track rank progression, and calculate flight hours</Li>
          <Li>To review and record PIREP submissions</Li>
          <Li>To deliver Discord notifications — PIREP status updates, rank promotions, and inactivity notices — via our Discord bot and server webhooks</Li>
          <Li>To record voluntary UPI contributions confirmed by members</Li>
          <Li>To assign or revoke Discord roles corresponding to your rank or Lotus Privé pledge status</Li>
          <Li>To generate aggregate statistics displayed on the public stats page — no individual data is exposed</Li>
        </Section>

        <Section title="4. Third-Party Services">
          <P><Strong>Discord</Strong> — <A href="https://discord.com/privacy">discord.com/privacy</A></P>
          <P>
            Used for authentication and for delivering bot DMs and webhook notifications. Your Discord ID
            is shared with Discord when our bot assigns roles or sends you a message.
          </P>

          <P><Strong>UPI payment apps</Strong></P>
          <P>
            Contributions are paid manually through the UPI app selected by the member. We only receive
            the member's in-app confirmation and record the amount, goal, IFC name, and optional Discord ID.
            We do not collect card, UPI, or bank account credentials.
          </P>

          <P><Strong>Vercel</Strong></P>
          <P>
            Our platform is hosted on Vercel's infrastructure. Request and edge-network logs may be
            processed by Vercel under their data processing agreement.
          </P>

          <P><Strong>Neon PostgreSQL &amp; Upstash Redis</Strong></P>
          <P>
            Pilot profile and PIREP data is stored in a PostgreSQL database hosted by Neon, Inc.
            Contribution totals, goal progress, and session caches are stored in Upstash Redis. Both
            providers are contractually bound to handle data securely.
          </P>

          <P><Strong>Infinite Flight Live API</Strong></P>
          <P>
            We query the Infinite Flight Live API using your IF user UUID to fetch your last ATC session.
            This is a read-only lookup — no personal data beyond the UUID is transmitted.
          </P>

          <P><Strong>SimBrief (Navigraph)</Strong></P>
          <P>
            Flight planning requests are routed through the SimBrief API using your SimBrief pilot ID.
            No personal data beyond the pilot ID and routing preferences is transmitted.
          </P>
        </Section>

        <Section title="5. Data Retention">
          <Li><Strong>Pilot profiles and PIREPs</Strong> — retained for as long as your account is active. On deletion request, personally identifiable data is removed within 30 days.</Li>
          <Li><Strong>Contribution records</Strong> — retained as financial records. Your IFC name and payment reference remain; your Discord ID can be anonymised on request.</Li>
          <Li><Strong>Session tokens</Strong> — expire automatically after 30 days of inactivity.</Li>
          <Li><Strong>Lotus Privé showcase</Strong> — your avatar and IFC name are removed after the monthly pledge grace period lapses.</Li>
        </Section>

        <Section title="6. Your Rights">
          <P>You have the right to:</P>
          <Li>Request a copy of the personal data we hold about you</Li>
          <Li>Request correction of inaccurate data</Li>
          <Li>Request deletion of your account and associated personal data</Li>
          <Li>Withdraw consent for optional uses such as the Lotus Privé showcase</Li>
          <P>
            Email <A href={`mailto:${CONTACT}`}>{CONTACT}</A> with the subject line "Privacy Request".
            We will respond within 30 days.
          </P>
        </Section>

        <Section title="7. Cookies">
          <P>
            We use a single first-party HTTP-only cookie to maintain your authenticated session via
            NextAuth.js. This cookie is strictly necessary for the platform to function and does not
            track you across other websites. We do not use advertising, analytics, or tracking cookies.
            Manual UPI payments open outside the browser in your selected payment app. Those apps may apply
            their own privacy and cookie policies.
          </P>
        </Section>

        <Section title="8. Security">
          <P>
            We implement HTTPS for all data in transit, HTTP-only session cookies, server-side
            authentication checks on all protected endpoints, and restricted staff-only administrative tools.
            In the event of a breach affecting your personal information,
            we will notify affected members via Discord or email within a reasonable timeframe.
          </P>
        </Section>

        <Section title="9. Children's Privacy">
          <P>
            The platform is open to users aged 13 and above, consistent with Discord's minimum age
            requirement. We do not knowingly collect data from children under 13. If you believe a
            child under 13 has registered, contact <A href={`mailto:${CONTACT}`}>{CONTACT}</A> and we
            will remove the account promptly.
          </P>
        </Section>

        <Section title="10. Governing Law">
          <P>
            This policy is governed by the laws of India, including the Information Technology Act 2000,
            the IT (Reasonable Security Practices) Rules 2011, and the Digital Personal Data Protection
            Act 2023. Any disputes are subject to the jurisdiction of courts in India.
          </P>
        </Section>

        <Section title="11. Changes to This Policy">
          <P>
            We may update this policy from time to time. The date at the top reflects the most recent
            revision. For significant changes, we will post an announcement in our Discord server.
            Continued use of the platform after changes constitutes acceptance.
          </P>
        </Section>

        <Section title="12. Contact">
          <P>
            For privacy questions, data requests, or concerns:{' '}
            <A href={`mailto:${CONTACT}`}>{CONTACT}</A>
          </P>
        </Section>

        {/* Footer rule */}
        <Box mt={14} pt={6} borderTop="1px solid #e5e7eb">
          <Text fontSize="12px" color="#9ca3af">
            Indian Virtual · <A href="/terms">Terms of Service</A> · <A href={`mailto:${CONTACT}`}>{CONTACT}</A>
          </Text>
        </Box>

      </Box>
    </Box>
  )
}
