import {
  FaCrown,
  FaMountain,
  FaClockRotateLeft,
  FaSun,
  FaEarthOceania,
  FaLandmark,
  FaPlaneUp,
  FaEarthAmericas,
  FaRoute,
  FaTree,
  FaCompass,
  FaTriangleExclamation,
  FaBoxesPacking,
  FaMountainSun,
  FaChessRook,
  FaGopuram,
  FaUmbrellaBeach,
  FaWheatAwn,
  FaWater,
  FaRoad,
  FaSnowflake,
  FaPaw,
  FaMosque,
  FaFan,
  FaVolcano,
  FaDragon,
  FaBuilding,
  FaTag,
  FaFeather,
  FaMonument,
  FaHippo,
  FaBridge,
  FaFish,
  FaGasPump,
  FaFeatherPointed,
  FaSailboat,
} from 'react-icons/fa6'

// ─── Trail types ───────────────────────────────────────────────────────────────
// The directory groups every trail under one of these three headings.

export const TYPES = [
  { key: 'circuit', title: 'Sequenced Circuits' },
  { key: 'collection', title: 'Highlight Collections' },
  { key: 'cargo', title: 'Cargo & Special Ops' },
]

// ─── City → ICAO lookup ─────────────────────────────────────────────────────────
// Lets the leg rows render each airport as "City (ICAO)" without repeating the
// code in every leg object.

export const ICAO = {
  Delhi: 'VIDP', Mumbai: 'VABB', Bengaluru: 'VOBL', Chennai: 'VOMM', Kolkata: 'VECC',
  Hyderabad: 'VOHS', Leh: 'VILH', Srinagar: 'VISR', Jammu: 'VIJU', Kozhikode: 'VOCL',
  Kannur: 'VOKN', Mangalore: 'VOML', Kochi: 'VOCI', Guwahati: 'VEGT', Imphal: 'VEIM',
  Agartala: 'VEAT', Aizawl: 'VELP', Dibrugarh: 'VEMN', Jaipur: 'VIJP', Jodhpur: 'VIJO',
  Jaisalmer: 'VIJR', Varanasi: 'VEBN', Bhubaneswar: 'VEBS', Tirupati: 'VOTP',
  'Port Blair': 'VOPB', Amritsar: 'VIAR', Ahmedabad: 'VAAH', Thiruvananthapuram: 'VOTV',
  'New York JFK': 'KJFK', 'Washington Dulles': 'KIAD', Chicago: 'KORD',
  'San Francisco': 'KSFO', 'Los Angeles': 'KLAX', Houston: 'KIAH', Toronto: 'CYYZ',
  Adelaide: 'YPAD', Sydney: 'YSSY', Melbourne: 'YMML', Perth: 'YPPH', Auckland: 'NZAA',
  Queenstown: 'NZQN', 'Coffs Harbour': 'YCFS', Brisbane: 'YBBN', 'Port Macquarie': 'YPMQ',
  Moscow: 'UUEE', Amsterdam: 'EHAM', Brussels: 'EBBR', Rome: 'LIRF', Vienna: 'LOWW',
  'London Heathrow': 'EGLL', 'London Gatwick': 'EGKK', Manchester: 'EGCC',
  Birmingham: 'EGBB', Edinburgh: 'EGPH', Innsbruck: 'LOWI', Madeira: 'LPMA',
  Gibraltar: 'LXGB', Zurich: 'LSZH', 'Düsseldorf': 'EDDL', Hamburg: 'EDDH',
  Munich: 'EDDM', Frankfurt: 'EDDF', Luxembourg: 'ELLX', Ljubljana: 'LJLJ',
  Stockholm: 'ESSA', Istanbul: 'LTFM', Warsaw: 'EPWA', Madrid: 'LEMD', Lisbon: 'LPPT',
  'Gran Canaria': 'GCLP', Reykjavik: 'BIKF', Paris: 'LFPG',
  Dubai: 'OMDB', 'Abu Dhabi': 'OMAA', Doha: 'OTHH', Muscat: 'OOMS', Jeddah: 'OEJN',
  Riyadh: 'OERK', Tashkent: 'UZTT',
  'Tokyo Haneda': 'RJTT', 'Tokyo Narita': 'RJAA', Osaka: 'RJBB', Okinawa: 'ROAH',
  'Seoul Incheon': 'RKSI', Singapore: 'WSSS', Hanoi: 'VVNB', Bangkok: 'VTBS',
  Phuket: 'VTSP', Manila: 'RPLL', Beijing: 'ZBAA', Guangzhou: 'ZGGG', Haikou: 'ZJHK',
  Vientiane: 'VLVT', Denpasar: 'WADD', Jakarta: 'WIII', 'Kuala Lumpur': 'WMKK',
  Honolulu: 'PHNL', Guam: 'PGUM', Anchorage: 'PANC',
  'Addis Ababa': 'HAAB', Nairobi: 'HKJK', Entebbe: 'HUEN', Kinshasa: 'FZAA',
  Johannesburg: 'FAOR', 'Cape Town': 'FACT', 'Victoria Falls': 'FVRG',
  'Port Louis': 'FIMP', 'Mahé': 'FSIA', Malé: 'VRMM', Lagos: 'DNMM',
  Cairo: 'HECA', Hurghada: 'HEGN', 'Sharm El Sheikh': 'HESH', Luxor: 'HELX',
  Marrakesh: 'GMMX',
  'Sao Paulo': 'SBGR', Santiago: 'SCEL', 'Rio de Janeiro': 'SBGL', Bogota: 'SKBO',
  'Buenos Aires': 'SAEZ', Guayaquil: 'SEGU', 'Mexico City': 'MMMX',
  'Panama City': 'MPTO', 'Punta Cana': 'MDPC', Cancún: 'MMUN', Kingston: 'MKJP',
  'St Maarten': 'TNCM', 'Port of Spain': 'TTPP', Georgetown: 'SYCJ',
  'Saint Lucia': 'TLPC', 'St Vincent': 'TVSA',
}

// ─── Aircraft badge helper ──────────────────────────────────────────────────────
// Turns a leg's aircraft string ("A359, Boeing 777-300ER") into short badges
// ("A359", "B777-300ER"), de-duplicated across the whole trail.

export function aircraftBadges(trail) {
  const out = []
  trail.legs.forEach(l =>
    l.ac.split(/[/,]/).forEach(tok => {
      let a = tok.trim().replace(/^Boeing /, 'B')
      if (!a) return
      if (!out.includes(a)) out.push(a)
    })
  )
  return out
}

// ─── Data ─────────────────────────────────────────────────────────────────────
// Every leg below is a real row from the INVA `routes` table. Where a trail is
// marked `sequenced`, its legs were chosen because one leg's arrival airport is
// the next leg's departure airport in the actual data — these are flyable,
// back-to-back itineraries, not a random sample. Suggested times are curatorial
// (the routes table carries no schedule), chosen to be operationally sensible.

export const TRAILS = [
  // ── Sequenced Circuits ──────────────────────────────────────────────────────
  {
    id: 'durbar',
    name: 'The Durbar Day Shuttle',
    tagline: 'A day in the life of the trunk network.',
    icon: FaCrown,
    type: 'circuit',
    color: '#2b4bee',
    bg: '#EFF3FF',
    border: '#C7D2FE',
    region: 'Domestic India · Sequenced',
    stat: '4 legs · 8h50m duty',
    sequenced: true,
    description:
      "Every real airline runs its narrowbodies hard, and Air India's domestic A320 family is no exception. This is one aircraft's plausible duty day on the trunk network — four sectors, three quick layovers, and a return to base before evening. Fly it exactly as scheduled below, or use it as a template for your own multi-sector duty day.",
    itinerary: [
      '06:00 IST — Depart Delhi (VIDP)',
      '08:00 — Arrive Mumbai (VABB) · 45m layover',
      '08:45 — Depart Mumbai',
      '10:05 — Arrive Bengaluru (VOBL) · 45m layover',
      '10:50 — Depart Bengaluru',
      '11:50 — Arrive Chennai (VOMM) · 45m layover',
      '12:35 — Depart Chennai',
      '14:50 — Arrive back at Delhi (VIDP)',
    ],
    legs: [
      { fn: 'AI2995', from: 'Delhi', to: 'Mumbai', ac: 'A320/A321', block: '02:00' },
      { fn: 'AI603', from: 'Mumbai', to: 'Bengaluru', ac: 'A320', block: '01:20' },
      { fn: 'AI525', from: 'Bengaluru', to: 'Chennai', ac: 'A320', block: '01:00' },
      { fn: 'AI538', from: 'Chennai', to: 'Delhi', ac: 'A320/A321', block: '02:15' },
    ],
  },
  {
    id: 'himalayan',
    name: 'The Himalayan Frontier Circuit',
    tagline: 'A morning window, four thin-air landings.',
    icon: FaMountain,
    type: 'circuit',
    color: '#0369A1',
    bg: '#F0F9FF',
    border: '#BAE6FD',
    region: 'Domestic India · Sequenced',
    stat: '4 legs · 6h00m loop',
    sequenced: true,
    description:
      "Leh sits at 10,682 feet, ringed by peaks over 20,000, and in the real world it's a morning-only airport — thermal turbulence off the mountains makes afternoon approaches too rough to schedule. This circuit respects that constraint. All four legs are flown before noon: Delhi up onto the Ladakh plateau, over to Srinagar's Kashmir valley, down to Jammu, and back to the plains — a complete tour of India's most demanding domestic terrain in one sitting.",
    itinerary: [
      '06:00 IST — Depart Delhi (VIDP)',
      '07:15 — Arrive Leh (VILH) · 40m layover',
      '07:55 — Depart Leh',
      '08:35 — Arrive Srinagar (VISR) · 40m layover',
      '09:15 — Depart Srinagar',
      '10:05 — Arrive Jammu (VIJU) · 40m layover',
      '10:45 — Depart Jammu',
      '12:00 — Arrive back at Delhi (VIDP)',
    ],
    legs: [
      { fn: 'AI445', from: 'Delhi', to: 'Leh', ac: 'A320', block: '01:15' },
      { fn: 'AI448', from: 'Leh', to: 'Srinagar', ac: 'A320', block: '00:40' },
      { fn: 'IX2565', from: 'Srinagar', to: 'Jammu', ac: 'A320', block: '00:50' },
      { fn: 'AIH822', from: 'Jammu', to: 'Delhi', ac: 'A320/A321', block: '01:15' },
    ],
  },
  {
    id: 'malabar',
    name: 'The Malabar Tabletop Circuit',
    tagline: 'Three runways with no room for error.',
    icon: FaTriangleExclamation,
    type: 'circuit',
    color: '#B91C1C',
    bg: '#FEF2F2',
    border: '#FECACA',
    region: 'Domestic India · Sequenced',
    stat: '4 legs · 4h30m loop',
    sequenced: true,
    description:
      "Kannur, Kozhikode and Mangalore are hemmed in by the Western Ghats and built on plateaus, not plains — tabletop runways with a drop at both ends and precisely zero margin for a long landing. Air India Express flies all three daily. This circuit strings the coastline together: Kozhikode out to Kannur, a short hop down to Mangalore, and back the way you came, entirely on the 737 family.",
    itinerary: [
      '07:00 IST — Depart Kozhikode (VOCL)',
      '07:45 — Arrive Kannur (VOKN) · 35m layover',
      '08:20 — Depart Kannur',
      '09:00 — Arrive Mangalore (VOML) · 35m layover',
      '09:35 — Depart Mangalore',
      '10:15 — Arrive back at Kannur (VOKN) · 35m layover',
      '10:50 — Depart Kannur',
      '11:30 — Arrive back at Kozhikode (VOCL)',
    ],
    legs: [
      { fn: 'IX5016H', from: 'Kozhikode', to: 'Kannur', ac: 'Boeing 737 MAX', block: '00:45' },
      { fn: 'IX890H', from: 'Kannur', to: 'Mangalore', ac: 'Boeing 737-800', block: '00:40' },
      { fn: 'IX891H', from: 'Mangalore', to: 'Kannur', ac: 'Boeing 737-800', block: '00:40' },
      { fn: 'IX369H', from: 'Kannur', to: 'Kozhikode', ac: 'Boeing 737 MAX', block: '00:40' },
    ],
  },
  {
    id: 'retro',
    name: 'The Retro Trail',
    tagline: 'Some liveries never really retire.',
    icon: FaClockRotateLeft,
    type: 'circuit',
    color: '#B45309',
    bg: '#FFFBEB',
    border: '#FDE68A',
    region: 'Heritage & Nostalgia',
    stat: '2 legs sequenced + 4 highlights',
    sequenced: true,
    description:
      "AIH is INVA's living museum — a heritage callsign that keeps the Boeing 747-400 flying the long-haul rotations that built Air India's reputation, upper deck and all. Its flagship routing is a real echo of how the Jumbo used to work a network: pick up the flight in Bengaluru, work the domestic leg into Mumbai, then push on through the night to New York on the same airframe. Alongside it, 9W keeps Jet Airways' widebodies airborne on routes the airline itself never got to finish.",
    itinerary: [
      '20:00 IST — Depart Bengaluru (VOBL)',
      '21:30 — Arrive Mumbai (VABB) · 1h00 layover, same airframe',
      '22:30 — Depart Mumbai for New York',
      '14:00 (+1, local) — Arrive New York JFK, 15h30m after Mumbai',
    ],
    legs: [
      { fn: 'AIH171 (A)', from: 'Bengaluru', to: 'Mumbai', ac: 'Boeing 747-400', block: '01:30' },
      { fn: 'AIH171 (B)', from: 'Mumbai', to: 'New York JFK', ac: 'Boeing 747-400', block: '15:30' },
      { fn: 'AIH01', from: 'Delhi', to: 'Adelaide', ac: 'Boeing 747-400', block: '11:00', note: 'Suggested depart 22:00 IST — overnight Jumbo redeye' },
      { fn: 'AIH11', from: 'Delhi', to: 'Moscow', ac: 'Boeing 747-400', block: '06:00', note: 'Suggested depart 01:00 IST' },
      { fn: '9W126', from: 'Mumbai', to: 'Amsterdam', ac: 'A330-300', block: '08:55', note: 'Suggested depart 02:30 IST' },
      { fn: '9W222', from: 'Brussels', to: 'Toronto', ac: 'A330-300/777-300ER', block: '07:45', note: 'Suggested depart 11:00 local' },
    ],
  },
  {
    id: 'european-relay',
    name: 'The European Relay',
    tagline: 'Two gateways, one destination: the United States.',
    icon: FaLandmark,
    type: 'circuit',
    color: '#6D28D9',
    bg: '#F9F5FF',
    border: '#DDD6FE',
    region: 'Europe · Sequenced',
    stat: '2 chained routings, 4 legs total',
    sequenced: true,
    description:
      "Not every Air India widebody has the range for Delhi–New York nonstop, so the network keeps two European tech-stops alive for the aircraft that need them — a real reflection of how mixed-range long-haul fleets actually get scheduled. Pick your gateway: Rome for JFK, or Vienna for the American Midwest. Same concept, different continent on the other end.",
    itinerary: [
      'ROME BRIDGE — Depart Delhi 01:30 IST · AI101 (A) · block 9h20m',
      '≈1h30 layover at Rome Fiumicino (LIRF), same airframe',
      'Depart Rome · AI101 (B) · block 8h25m · arrive New York JFK',
      '',
      'VIENNA BRIDGE — Depart Delhi 09:15 IST · AI103 (A) · block 9h39m',
      '≈1h30 layover at Vienna (LOWW), same airframe',
      'Depart Vienna · AI103 (B) · block 8h30m · arrive Washington Dulles',
    ],
    legs: [
      { fn: 'AI101 (A)', from: 'Delhi', to: 'Rome', ac: 'A350-900', block: '09:20' },
      { fn: 'AI101 (B)', from: 'Rome', to: 'New York JFK', ac: 'A350-900', block: '08:25' },
      { fn: 'AI103 (A)', from: 'Delhi', to: 'Vienna', ac: 'Boeing 787-8', block: '09:39' },
      { fn: 'AI103 (B)', from: 'Vienna', to: 'Washington Dulles', ac: 'Boeing 787-8', block: '08:30' },
      { fn: 'AI127 (A)', from: 'Delhi', to: 'Vienna', ac: 'Boeing 777-300ER', block: '09:05', note: 'Alternate Vienna routing' },
      { fn: 'AI127 (B)', from: 'Vienna', to: 'Chicago', ac: 'Boeing 777-300ER', block: '09:15', note: "Alternate: lands O'Hare instead of Dulles" },
    ],
  },
  {
    id: 'kolkata-relay',
    name: 'The Kolkata Relay',
    tagline: 'The longest duty in the network, there and back.',
    icon: FaPlaneUp,
    type: 'circuit',
    color: '#1E3A8A',
    bg: '#EFF6FF',
    border: '#BFDBFE',
    region: 'North America · Sequenced',
    stat: '4 legs · 35h40m round trip',
    sequenced: true,
    description:
      "AI183 doesn't originate in San Francisco-bound form — it starts as a Delhi–Kolkata domestic hop, and the same 777-300ER that lands in Kolkata keeps going, westbound, for another fifteen hours. It's the single longest continuous rotation on the INVA network, and it has a genuine round trip: the return working number, AI4174, retraces the exact same relay in reverse. Fly the whole thing and you've logged nearly a day and a half of block time on one aircraft type.",
    itinerary: [
      'OUTBOUND — Depart Delhi 10:00 IST · AI183 (A) · block 1h40m',
      'Arrive Kolkata ≈11:40 IST · 1h00 layover, same airframe continues',
      'Depart Kolkata 12:40 IST · AI183 (B) · block 15h10m',
      'Arrive San Francisco ≈14:20 local (same calendar day, date-line gain)',
      '',
      'RETURN — Depart San Francisco 22:00 local · AI4174 (A) · block 16h35m',
      'Arrive Kolkata ≈04:05 IST · 1h00 layover, same airframe continues',
      'Depart Kolkata 05:05 IST · AI4174 (B) · block 2h15m',
      'Arrive Delhi 07:20 IST',
    ],
    legs: [
      { fn: 'AI183 (A)', from: 'Delhi', to: 'Kolkata', ac: 'Boeing 777-300ER', block: '01:40' },
      { fn: 'AI183 (B)', from: 'Kolkata', to: 'San Francisco', ac: 'Boeing 777-300ER', block: '15:10' },
      { fn: 'AI4174 (A)', from: 'San Francisco', to: 'Kolkata', ac: 'Boeing 777-300ER', block: '16:35' },
      { fn: 'AI4174 (B)', from: 'Kolkata', to: 'Delhi', ac: 'Boeing 777-300ER', block: '02:15' },
    ],
  },
  {
    id: 'circumnavigator',
    name: 'The Circumnavigator',
    tagline: 'Home to home, the long way around.',
    icon: FaEarthAmericas,
    type: 'circuit',
    color: '#9D174D',
    bg: '#FDF2F8',
    border: '#FBCFE8',
    region: 'Round-the-World · Sequenced',
    stat: '5 legs · ~51h25m · 3 A380 sectors',
    sequenced: true,
    description:
      "The most ambitious itinerary in the collection: a full circumnavigation using four airlines and three double-decker superjumbo sectors, starting and ending in Delhi. It isn't one continuous rotation — it's a challenge, best flown over several sittings — but every leg below is a real route in the network, and each hands off cleanly to the next at a shared airport.",
    itinerary: [
      'Depart Delhi 20:00 IST · AI4309 · block 3h10m · arrive Dubai',
      '2h00 layover · connect to Emirates',
      'Depart Dubai · EK215 · block 15h20m (A380) · arrive Los Angeles',
      '2h30 layover · connect to Qantas',
      'Depart Los Angeles ~21:00 local · QF12 · block 15h10m (A380) · arrive Sydney',
      '2h00 layover · connect to Qatar Airways',
      'Depart Sydney · QR909 · block 14h45m (A380) · arrive Doha',
      '2h00 layover · connect back to Air India',
      'Depart Doha · AI2284 · block 3h00m · arrive home in Delhi',
    ],
    legs: [
      { fn: 'AI4309', from: 'Delhi', to: 'Dubai', ac: 'Boeing 787-8', block: '03:10' },
      { fn: 'EK215', from: 'Dubai', to: 'Los Angeles', ac: 'A380-800', block: '15:20' },
      { fn: 'QF12', from: 'Los Angeles', to: 'Sydney', ac: 'A380-800', block: '15:10' },
      { fn: 'QR909', from: 'Sydney', to: 'Doha', ac: 'A380-800', block: '14:45' },
      { fn: 'AI2284', from: 'Doha', to: 'Delhi', ac: 'A320', block: '03:00' },
    ],
  },
  {
    id: 'istanbul-samba',
    name: 'The Samba Bridge',
    tagline: 'Istanbul to South America, and all the way back.',
    icon: FaBridge,
    type: 'circuit',
    color: '#9F1239',
    bg: '#FFF1F2',
    border: '#FECDD3',
    region: 'Turkey → South America · Sequenced',
    stat: '4 legs · 32h55m round trip',
    sequenced: true,
    description:
      "Turkish Airlines runs its own tech-stop chain to the far side of the Atlantic — the same A350 that leaves Istanbul works São Paulo, then continues down to Santiago before turning around and retracing every leg home. It's the European Relay concept in another hemisphere: one airframe, two continents, four legs that hand off cleanly at a shared hub.",
    itinerary: [
      'OUTBOUND — Depart Istanbul (LTFM) · TK215 (A) · block 13h20m',
      '≈2h layover at São Paulo (SBGR), same airframe continues',
      'Depart São Paulo · TK215 (B) · block 4h10m · arrive Santiago (SCEL)',
      '',
      'RETURN — Depart Santiago · TK216 (A) · block 3h10m',
      '≈2h layover at São Paulo (SBGR)',
      'Depart São Paulo · TK216 (B) · block 12h15m · arrive Istanbul (LTFM)',
    ],
    legs: [
      { fn: 'TK215 (A)', from: 'Istanbul', to: 'Sao Paulo', ac: 'A350-900', block: '13:20' },
      { fn: 'TK215 (B)', from: 'Sao Paulo', to: 'Santiago', ac: 'A350-900', block: '04:10' },
      { fn: 'TK216 (A)', from: 'Santiago', to: 'Sao Paulo', ac: 'A350-900', block: '03:10' },
      { fn: 'TK216 (B)', from: 'Sao Paulo', to: 'Istanbul', ac: 'A350-900', block: '12:15' },
    ],
  },
  {
    id: 'trans-pacific',
    name: 'The Trans-Pacific Island Hop',
    tagline: 'Hopping the loneliest stretch of ocean on the map.',
    icon: FaFish,
    type: 'circuit',
    color: '#0369A1',
    bg: '#F0F9FF',
    border: '#BAE6FD',
    region: 'Pacific · Sequenced',
    stat: '2 legs · 15h30m',
    sequenced: true,
    description:
      "Batik Air Malaysia threads a single 737-900 across the Pacific's emptiest water — Honolulu out to Guam, refuel, then onward to Kuala Lumpur. Two legs, three island systems, and more open ocean between waypoints than almost anywhere else you can fly. A genuine chained routing for pilots who like their diversions few and far between.",
    itinerary: [
      'Depart Honolulu (PHNL) · OD1 (B) · block 8h00m',
      'Arrive Guam (PGUM) · refuel & layover, same airframe continues',
      'Depart Guam · OD1 (C) · block 7h30m · arrive Kuala Lumpur (WMKK)',
    ],
    legs: [
      { fn: 'OD1 (B)', from: 'Honolulu', to: 'Guam', ac: 'Boeing 737-900', block: '08:00' },
      { fn: 'OD1 (C)', from: 'Guam', to: 'Kuala Lumpur', ac: 'Boeing 737-900', block: '07:30' },
    ],
  },

  // ── Highlight Collections ───────────────────────────────────────────────────
  {
    id: 'golden-sands',
    name: 'The Golden Sands & Haj Bridge',
    tagline: 'The corridor that carries the most people, and the most meaning.',
    icon: FaSun,
    type: 'collection',
    color: '#C2410C',
    bg: '#FFF7ED',
    border: '#FED7AA',
    region: 'Middle East & the Gulf',
    stat: '5 hand-picked legs',
    sequenced: false,
    description:
      "No corridor on the map carries more real-world weight. Delhi and Mumbai run the daily commuter shuttle to Dubai; Kochi's Air India Express service exists because of how many Keralites work in the Gulf. And every Haj and Umrah season, Jeddah becomes the busiest single destination on the network — Air India, Air India Express and the heritage 747 all running charter-density schedules from cities across the south. This trail is that corridor, in five legs.",
    legs: [
      { fn: 'AI4309', from: 'Delhi', to: 'Dubai', ac: 'Boeing 787-8', block: '03:10', note: 'Suggested depart 20:00 IST — evening commuter bank' },
      { fn: 'IX435', from: 'Kochi', to: 'Dubai', ac: 'Boeing 737-800', block: '04:00', note: 'Suggested depart 03:00 IST — the Gulf-diaspora red-eye' },
      { fn: 'AI2255', from: 'Delhi', to: 'Jeddah', ac: 'A320', block: '05:50', note: 'Suggested depart 04:00 IST — Umrah timing' },
      { fn: 'AIH959', from: 'Kozhikode', to: 'Jeddah', ac: 'Boeing 747-400', block: '05:50', note: 'Suggested depart 23:00 IST — Haj-season heritage charter' },
      { fn: 'AI2233', from: 'Mumbai', to: 'Muscat', ac: 'A320', block: '02:10', note: 'Suggested depart 05:30 IST' },
    ],
  },
  {
    id: 'southern-cross',
    name: 'The Southern Cross Trail',
    tagline: 'Down under, the long way.',
    icon: FaEarthOceania,
    type: 'collection',
    color: '#0F766E',
    bg: '#F0FDFA',
    border: '#99F6E4',
    region: 'Australia & the Pacific',
    stat: '4 hand-picked legs',
    sequenced: false,
    description:
      "Eleven-plus hours before the coast even comes into view. Air India's 787s cover Sydney and Melbourne on the modern roster; the heritage 747-400, flying as AIH, still holds down Adelaide the way the Jumbo always did; and the single longest sector on this trail runs all the way to Auckland. Full-tank planning, real fatigue management, no shortcuts.",
    legs: [
      { fn: 'AI301', from: 'Sydney', to: 'Delhi', ac: 'Boeing 787-8', block: '11:45', note: 'Suggested depart 23:30 local — the redeye home' },
      { fn: 'AI310', from: 'Mumbai', to: 'Melbourne', ac: 'Boeing 787-8', block: '11:00', note: 'Suggested depart 23:45 IST' },
      { fn: 'AIH1306', from: 'Delhi', to: 'Auckland', ac: 'Boeing 787-8', block: '16:30', note: 'Suggested depart 21:00 IST — longest leg on this trail' },
      { fn: 'AIH01', from: 'Delhi', to: 'Adelaide', ac: 'Boeing 747-400', block: '11:00', note: 'Suggested depart 22:30 IST — the Jumbo still flies it' },
    ],
  },
  {
    id: 'silk-route',
    name: 'The Silk Route Trail',
    tagline: "India's oldest trading partners, its newest metal.",
    icon: FaRoute,
    type: 'collection',
    color: '#15803D',
    bg: '#F0FDF4',
    border: '#BBF7D0',
    region: 'East & Southeast Asia',
    stat: '5 hand-picked legs',
    sequenced: false,
    description:
      "East of India is where the partner network gets genuinely exotic — a Korean Air 747-8 into JFK, EVA and Singapore Airlines A380s on their regional trunk routes, Vietnam's newest widebodies working the Hanoi corridor, and the last echo of Vistara's purple tail still climbing out toward Tokyo. Different airline, different livery, every single leg.",
    legs: [
      { fn: 'KE81', from: 'New York JFK', to: 'Seoul Incheon', ac: 'Boeing 747-8 / A380', block: '14:35', note: 'One of two 747-8s left flying passengers anywhere on the network' },
      { fn: 'SQ637', from: 'Tokyo Narita', to: 'Singapore', ac: 'A380 / 787-10 / 777-300ER', block: '07:00', note: 'Suggested depart 09:00 local' },
      { fn: 'VN980', from: 'Delhi', to: 'Hanoi', ac: 'A350-900 / 787-9', block: '03:45', note: 'Suggested depart 14:00 IST' },
      { fn: 'UK83H', from: 'Delhi', to: 'Tokyo Haneda', ac: 'Boeing 787-9', block: '07:45', note: 'The last Vistara-liveried route still on the board' },
      { fn: 'TG910', from: 'Bangkok', to: 'London Heathrow', ac: 'A380 / 777-300ER', block: '12:30', note: 'Suggested depart 23:30 local' },
    ],
  },
  {
    id: 'baobab',
    name: 'The Baobab Trail',
    tagline: "India's oldest bridge to Africa, rebuilt.",
    icon: FaTree,
    type: 'collection',
    color: '#4D7C0F',
    bg: '#F7FEE7',
    border: '#D9F99D',
    region: 'Africa & the Indian Ocean',
    stat: '5 hand-picked legs',
    sequenced: false,
    description:
      "Long before Gulf hubs dominated the map, dhow trade and colonial-era aviation tied India's west coast to East Africa. This trail rebuilds that link — Ethiopian's Addis Ababa hub reaching both Mumbai and, remarkably, Sao Paulo on the same 777; Kenya Airways bridging Nairobi to Johannesburg; Jet Airways' revived widebody doing the same Mumbai–Johannesburg run; and Air Mauritius, the quiet thread connecting Delhi to Port Louis and one of the oldest Indian diaspora communities anywhere.",
    legs: [
      { fn: 'ET610', from: 'Addis Ababa', to: 'Mumbai', ac: 'Boeing 777-200LR/787-8', block: '05:30', note: 'Suggested depart 23:00 local' },
      { fn: 'ET506', from: 'Addis Ababa', to: 'Sao Paulo', ac: 'Boeing 777-200LR', block: '12:20', note: 'An Africa–South America bridge, rare on any network' },
      { fn: 'KQ761', from: 'Nairobi', to: 'Johannesburg', ac: 'Boeing 787-8', block: '04:00', note: 'Suggested depart 08:00 local' },
      { fn: '9W116', from: 'Mumbai', to: 'Johannesburg', ac: 'A330-300', block: '09:00', note: 'Suggested depart 01:00 IST' },
      { fn: 'MK744', from: 'Port Louis', to: 'Delhi', ac: 'A330-900', block: '07:35', note: 'Air Mauritius, tracing the Indian Ocean diaspora route' },
    ],
  },
  {
    id: 'far-frontier',
    name: 'The Far Frontier Trail',
    tagline: 'For pilots chasing the routes no one else flies.',
    icon: FaCompass,
    type: 'collection',
    color: '#BE185D',
    bg: '#FDF2F8',
    border: '#FBCFE8',
    region: 'Latin America',
    stat: '4 hand-picked legs',
    sequenced: false,
    description:
      "No Indian carrier serves Latin America directly — which is exactly what makes this trail worth flying. Avianca's odd Bogota–London routing, GOL's Brazil-family metal linking Sao Paulo to Mexico City, a genuine colonial-era echo on the Lisbon–Rio run, and Copa threading Panama's hub down to Buenos Aires. A collector's trail for pilots who've already logged the rest of the map.",
    legs: [
      { fn: 'AV120', from: 'Bogota', to: 'London Heathrow', ac: 'Boeing 787-8', block: '10:00', note: 'Suggested depart 21:00 local' },
      { fn: 'VRG8670', from: 'Sao Paulo', to: 'Mexico City', ac: 'Boeing 777-200ER', block: '09:30', note: 'Suggested depart 23:30 local' },
      { fn: 'VRG8703', from: 'Lisbon', to: 'Rio de Janeiro', ac: 'Boeing 777-200ER', block: '09:30', note: 'The old Portugal–Brazil link, still flown daily' },
      { fn: 'CM167', from: 'Panama City', to: 'Buenos Aires', ac: 'Boeing 737 MAX', block: '07:10', note: 'Suggested depart 22:00 local' },
    ],
  },
  {
    id: 'toughest-approaches',
    name: "World's Toughest Approaches",
    tagline: 'Where the terrain briefing matters more than the METAR.',
    icon: FaTriangleExclamation,
    type: 'collection',
    color: '#78350F',
    bg: '#FEFCE8',
    border: '#FEF08A',
    region: 'Terrain & Technique · International',
    stat: '5 curated challenge airports',
    sequenced: false,
    description:
      "Domestic India already has Leh and the Malabar tabletops — this trail rounds up the rest of the world's genuine terrain and crosswind tests, all real legs on the network. Innsbruck's Alpine bowl, Queenstown's real-world night-flight ban, Madeira's cliffside crosswind runway, Gibraltar's runway that crosses an active road, and the low approach over Maho Beach into St Maarten. Brief the terrain before you brief the weather.",
    legs: [
      { fn: 'U22299', from: 'Manchester', to: 'Innsbruck', ac: 'A320', block: '02:10', note: 'Fly by day — valley circling approach between the Alps' },
      { fn: 'QF124', from: 'Queenstown', to: 'Sydney', ac: 'Boeing 737-800', block: '03:10', note: "Real Queenstown has no night flights — the terrain doesn't allow it" },
      { fn: 'U26402', from: 'Madeira', to: 'London Gatwick', ac: 'A320', block: '03:15', note: 'The runway is built out on stilts over the sea — mind the crosswind' },
      { fn: 'U26934', from: 'Gibraltar', to: 'Edinburgh', ac: 'A320', block: '03:00', note: 'The only runway anywhere that crosses a public road' },
      { fn: 'CM134', from: 'Panama City', to: 'St Maarten', ac: 'Boeing 737 MAX', block: '03:00', note: 'The low pass over Maho Beach on short final' },
    ],
  },
  {
    id: 'seven-sisters',
    name: 'The Seven Sisters Circuit',
    tagline: "Northeast India's own hub-and-spoke, far from any metro.",
    icon: FaMountainSun,
    type: 'collection',
    color: '#047857',
    bg: '#ECFDF5',
    border: '#A7F3D0',
    region: 'Domestic India · Northeast',
    stat: '5 hand-picked legs',
    sequenced: false,
    description:
      "Everything east of Bengal routes through Guwahati the way the rest of the country routes through Delhi. This is genuinely under-flown territory — short A320 and 737 hops between hill-country fields most pilots never visit, threading Imphal, Agartala, Aizawl and Dibrugarh off the region's single real hub.",
    legs: [
      { fn: 'AI889', from: 'Delhi', to: 'Guwahati', ac: 'A320', block: '02:30', note: 'The trunk feed into the region — Guwahati is the hub' },
      { fn: 'IX1142', from: 'Guwahati', to: 'Imphal', ac: 'Boeing 737 MAX', block: '01:05' },
      { fn: 'IX1192', from: 'Agartala', to: 'Guwahati', ac: 'Boeing 737 MAX', block: '00:50' },
      { fn: 'AIH710', from: 'Imphal', to: 'Aizawl', ac: 'A320', block: '00:45', note: 'A rare inter-spoke hop that skips the hub' },
      { fn: 'IX1186', from: 'Guwahati', to: 'Dibrugarh', ac: 'A320', block: '01:00' },
    ],
  },
  {
    id: 'pink-city',
    name: 'The Pink City & Thar Desert Trail',
    tagline: 'Forts, sand, and a surprisingly busy little airport.',
    icon: FaChessRook,
    type: 'collection',
    color: '#C026D3',
    bg: '#FDF4FF',
    border: '#F5D0FE',
    region: 'Domestic India · Rajasthan',
    stat: '6 hand-picked legs',
    sequenced: false,
    description:
      "Jaipur is far busier than its size suggests — 35 routes on the board, including its own Air India Express hop to Dubai and an Etihad link from Abu Dhabi. Around it, the desert cities of Jodhpur and tiny Jaisalmer round out a Rajasthan circuit built for fort-and-dune tourism rather than metro throughput.",
    legs: [
      { fn: 'AI1767', from: 'Delhi', to: 'Jaipur', ac: 'A320', block: '00:45', note: 'The Pink City shuttle from the capital' },
      { fn: 'AI612', from: 'Jaipur', to: 'Mumbai', ac: 'A320', block: '01:20' },
      { fn: 'AI2475', from: 'Delhi', to: 'Jodhpur', ac: 'A320', block: '01:10' },
      { fn: 'AI1765', from: 'Delhi', to: 'Jaisalmer', ac: 'A320', block: '01:35', note: 'Deep into the Thar, near the Pakistan frontier' },
      { fn: 'IX141', from: 'Jaipur', to: 'Dubai', ac: 'A320', block: '04:00', note: "Jaipur's own Gulf service" },
      { fn: 'EY5023', from: 'Abu Dhabi', to: 'Jaipur', ac: 'A321', block: '03:15', note: 'Etihad reaches Rajasthan directly' },
    ],
  },
  {
    id: 'pilgrims-path',
    name: "The Pilgrim's Path",
    tagline: "India's spiritual capitals, not its commercial ones.",
    icon: FaGopuram,
    type: 'collection',
    color: '#EA580C',
    bg: '#FFF7ED',
    border: '#FED7AA',
    region: 'Domestic India · Pilgrimage',
    stat: '4 hand-picked legs',
    sequenced: false,
    description:
      "Not every city on the network earns its traffic from business. Varanasi, Puri's gateway at Bhubaneswar and the temple town of Tirupati draw pilgrims by the millions — humble A320 sectors serving cities that matter far more than their size. A quieter, more contemplative kind of domestic flying.",
    legs: [
      { fn: 'AI2623', from: 'Delhi', to: 'Varanasi', ac: 'A320', block: '01:15', note: 'The oldest living city on the Ganges' },
      { fn: 'IX1023', from: 'Mumbai', to: 'Varanasi', ac: 'Boeing 737 MAX', block: '02:15' },
      { fn: 'AI499', from: 'Delhi', to: 'Bhubaneswar', ac: 'A321', block: '02:00', note: 'Gateway to the Jagannath temple at Puri' },
      { fn: 'AI2541', from: 'Tirupati', to: 'Hyderabad', ac: 'A320', block: '01:10', note: "One of the world's most-visited temple towns" },
    ],
  },
  {
    id: 'andaman',
    name: 'The Andaman Island Escape',
    tagline: 'Leave the mainland behind entirely.',
    icon: FaUmbrellaBeach,
    type: 'collection',
    color: '#0891B2',
    bg: '#ECFEFF',
    border: '#A5F3FC',
    region: 'Domestic India · Bay of Bengal',
    stat: '4 hand-picked legs',
    sequenced: false,
    description:
      "Port Blair sits a thousand kilometres out into the Bay of Bengal, reached from four mainland gateways and nowhere else. Every approach is an over-water arrival onto an island runway — the closest thing the domestic network has to an oceanic leg, and a genuine change of scenery from the metros.",
    legs: [
      { fn: 'AI485', from: 'Delhi', to: 'Port Blair', ac: 'A320', block: '03:50', note: 'The long haul out from the capital' },
      { fn: 'AIH549', from: 'Chennai', to: 'Port Blair', ac: 'A320', block: '02:00' },
      { fn: 'AIH787', from: 'Kolkata', to: 'Port Blair', ac: 'A320', block: '02:00' },
      { fn: 'AIH2508', from: 'Port Blair', to: 'Bengaluru', ac: 'A320', block: '02:30' },
    ],
  },
  {
    id: 'punjab-diaspora',
    name: 'The Punjab Diaspora Bridge',
    tagline: 'A small Indian city with a genuinely long-haul network.',
    icon: FaWheatAwn,
    type: 'collection',
    color: '#CA8A04',
    bg: '#FEFCE8',
    border: '#FEF08A',
    region: 'Domestic India → UK & Europe',
    stat: '4 hand-picked legs',
    sequenced: false,
    description:
      "Amritsar punches far above its weight. The spiritual heart of Sikhism runs widebody 787s direct to Birmingham and London Gatwick, a heritage tech-stop to Rome, and a heritage 747 link down to Mumbai — a route map shaped entirely by one of the largest and most established diaspora communities in the world.",
    legs: [
      { fn: 'AI117', from: 'Amritsar', to: 'Birmingham', ac: 'Boeing 787-8', block: '07:30', note: 'The Midlands has one of the UK’s largest Punjabi communities' },
      { fn: 'AI169', from: 'Amritsar', to: 'London Gatwick', ac: 'Boeing 787-8', block: '08:30' },
      { fn: 'AIH111', from: 'Amritsar', to: 'Rome', ac: 'Boeing 787-8', block: '07:10', note: 'A heritage-liveried European tech-stop' },
      { fn: 'AIH17', from: 'Mumbai', to: 'Amritsar', ac: 'Boeing 747-400', block: '02:00', note: 'The heritage Jumbo on a domestic leg' },
    ],
  },
  {
    id: 'indian-ocean-idylls',
    name: 'Indian Ocean Idylls',
    tagline: 'Honeymoon energy, short block times, big scenery.',
    icon: FaWater,
    type: 'collection',
    color: '#0D9488',
    bg: '#F0FDFA',
    border: '#99F6E4',
    region: 'Maldives & Seychelles',
    stat: '5 hand-picked legs',
    sequenced: false,
    description:
      "Two tiny island nations, four carriers converging. Air India and the heritage callsign reach Malé from Delhi and Bengaluru; Etihad and Qatar bring in the Gulf feed; and Ethiopian's 737 MAX connects the Seychelles onward to Addis Ababa. Short sectors, over-water approaches, and about as scenic as the network gets.",
    legs: [
      { fn: 'AI239', from: 'Delhi', to: 'Malé', ac: 'A320', block: '03:55' },
      { fn: 'AIH265', from: 'Bengaluru', to: 'Malé', ac: 'A320', block: '01:55', note: 'The shortest hop to the Maldives on the network' },
      { fn: 'EY260', from: 'Abu Dhabi', to: 'Malé', ac: 'Boeing 777-300ER', block: '04:10', note: 'A widebody on a leisure run' },
      { fn: 'QR678', from: 'Doha', to: 'Mahé', ac: 'A350-900 / 777', block: '04:10', note: 'Qatar into the Seychelles' },
      { fn: 'ET878', from: 'Mahé', to: 'Addis Ababa', ac: 'Boeing 737 MAX', block: '03:30', note: 'The island link back to the African hub' },
    ],
  },
  {
    id: 'silk-road-gateway',
    name: 'The Silk Road Gateway',
    tagline: 'One thread to Central Asia, and it is rare.',
    icon: FaRoad,
    type: 'collection',
    color: '#92400E',
    bg: '#FFFBEB',
    border: '#FDE68A',
    region: 'Central Asia',
    stat: '2 hand-picked legs',
    sequenced: false,
    description:
      "Uzbekistan Airways runs the only thread on the network reaching deep Central Asia — Tashkent to Delhi and Mumbai, and nothing else. Two routes total, but a genuinely rare flavour: a slice of the old Silk Road that no other carrier here touches, flown on an unusual mix of A320, 767 and 787 equipment.",
    legs: [
      { fn: 'HY421', from: 'Tashkent', to: 'Delhi', ac: 'A320 / 787-8', block: '02:20', note: 'The only Central Asian service on the board' },
      { fn: 'HY427', from: 'Tashkent', to: 'Mumbai', ac: 'A320', block: '04:35' },
    ],
  },
  {
    id: 'alpine-express',
    name: 'The Alpine Express',
    tagline: "Zurich's tight, fast, mixed-metal European hops.",
    icon: FaSnowflake,
    type: 'collection',
    color: '#0284C7',
    bg: '#F0F9FF',
    border: '#BAE6FD',
    region: 'Central Europe',
    stat: '3 hand-picked legs',
    sequenced: false,
    description:
      "A different kind of short-sector trail — alpine instead of subcontinental. Swiss works a tight web of sub-95-minute hops out of Zurich into Germany, flown on a genuinely mixed roster of A220s, A320-family jets and Embraers. Precision flying in busy European airspace, nothing over an hour and a half.",
    legs: [
      { fn: 'LX1016', from: 'Zurich', to: 'Düsseldorf', ac: 'A220-300 / A320', block: '01:35' },
      { fn: 'LX1052', from: 'Zurich', to: 'Hamburg', ac: 'A220-300 / A320', block: '01:30' },
      { fn: 'LX1100', from: 'Zurich', to: 'Munich', ac: 'A220-300 / A320', block: '00:55', note: 'A 55-minute inter-alpine dash' },
    ],
  },
  {
    id: 'brussels-africa',
    name: "Brussels' African Line",
    tagline: 'Multi-stop routings baked right into the flight number.',
    icon: FaPaw,
    type: 'collection',
    color: '#4D7C0F',
    bg: '#F7FEE7',
    border: '#D9F99D',
    region: 'Europe → Central Africa',
    stat: '3 hand-picked legs',
    sequenced: false,
    description:
      "Brussels Airlines still flies the colonial-era echoes of Belgium's African network, and the routings show it — each of these is a single flight number with a scheduled intermediate stop written into it. A330s down to Kinshasa via Luanda, Nairobi via Kigali, Entebbe via Bujumbura. Old-school multi-sector long-haul, exactly as filed.",
    legs: [
      { fn: 'SN359', from: 'Brussels', to: 'Kinshasa', ac: 'A330-300', block: '09:30', note: 'Routes via Luanda (FNLU) on the way south' },
      { fn: 'SN465', from: 'Brussels', to: 'Nairobi', ac: 'A330-300', block: '09:20', note: 'Via Kigali (HRYR)' },
      { fn: 'SN481', from: 'Brussels', to: 'Entebbe', ac: 'A330-300', block: '08:30', note: 'Via Bujumbura (HBBA)' },
    ],
  },
  {
    id: 'istanbul-crossroads',
    name: 'Istanbul Crossroads',
    tagline: 'One field, an absurd spread of destinations.',
    icon: FaMosque,
    type: 'collection',
    color: '#7C3AED',
    bg: '#F5F3FF',
    border: '#DDD6FE',
    region: 'Turkey · Global Hub',
    stat: '4 hand-picked legs',
    sequenced: false,
    description:
      "No single airport on the network reaches more of the world than Istanbul. Turkish Airlines fans out from one field to the Balkans, Scandinavia, the American Midwest and West Africa — pick any bearing and there's a route on it. This trail samples four wildly different sectors that all start at the same gate.",
    legs: [
      { fn: 'TK1061', from: 'Istanbul', to: 'Ljubljana', ac: 'A321 / 737-800', block: '02:00', note: 'A short Balkan hop' },
      { fn: 'TK1789', from: 'Istanbul', to: 'Stockholm', ac: 'A321 / 737-800', block: '03:10' },
      { fn: 'TK5', from: 'Istanbul', to: 'Chicago', ac: 'Boeing 777-300ER / 787-9', block: '10:45', note: 'The transatlantic flagship' },
      { fn: 'TK625', from: 'Istanbul', to: 'Lagos', ac: 'A330-300', block: '06:25', note: 'Deep into West Africa' },
    ],
  },
  {
    id: 'rising-sun',
    name: 'The Rising Sun Network',
    tagline: 'Ultra-long-haul next to a tiny domestic hop, same airline.',
    icon: FaFan,
    type: 'collection',
    color: '#DC2626',
    bg: '#FEF2F2',
    border: '#FECACA',
    region: 'Japan · ANA',
    stat: '3 hand-picked legs',
    sequenced: false,
    description:
      "ANA's roster runs the full spectrum in one livery: a twelve-hour 777 haul from Houston to Tokyo, a Dreamliner across the Pacific from Mexico City, and — for contrast — a 90-minute A320 skip from Osaka out to Okinawa. Fly all three and you've bracketed the entire range of what a single flag carrier does.",
    legs: [
      { fn: 'NH113', from: 'Houston', to: 'Tokyo Haneda', ac: 'Boeing 777-300ER', block: '12:20', note: 'A twelve-hour transpacific haul' },
      { fn: 'NH179', from: 'Mexico City', to: 'Tokyo Narita', ac: 'Boeing 787-8', block: '11:44' },
      { fn: 'NH1731', from: 'Osaka', to: 'Okinawa', ac: 'A320', block: '01:30', note: 'The domestic island hop — same tail' },
    ],
  },
  {
    id: 'indonesian-archipelago',
    name: 'The Indonesian Archipelago',
    tagline: 'Garuda, Batik and Lion, all hopping the same islands.',
    icon: FaVolcano,
    type: 'collection',
    color: '#C2410C',
    bg: '#FFF7ED',
    border: '#FED7AA',
    region: 'Indonesia & Australasia',
    stat: '4 hand-picked legs',
    sequenced: false,
    description:
      "Three carriers, one sprawling archipelago. Garuda holds down the Jakarta–Denpasar shuttle and the long run to Sydney; Batik Air pushes an A320 all the way to Melbourne; and Lion Air's oddest routing threads Jakarta to Jeddah with a stop at Thiruvananthapuram. Island-hopping at every scale, from 90-minute shuttle to Haj-pilgrim long-haul.",
    legs: [
      { fn: 'GA401', from: 'Denpasar', to: 'Jakarta', ac: 'A330-300', block: '01:30', note: 'The Bali–Jakarta shuttle' },
      { fn: 'GA712', from: 'Jakarta', to: 'Sydney', ac: 'A330 / 777-300ER', block: '06:45' },
      { fn: 'ID6003', from: 'Denpasar', to: 'Melbourne', ac: 'A320', block: '05:40', note: 'A narrowbody pushed to its range' },
      { fn: 'JT70', from: 'Jakarta', to: 'Jeddah', ac: 'Boeing 737-900', block: '11:00', note: 'Via Thiruvananthapuram (VOTV) — a Haj-pilgrim routing' },
    ],
  },
  {
    id: 'hainan-silk-road',
    name: "Hainan's Silk Road",
    tagline: "Beijing's reach, one Chinese carrier.",
    icon: FaDragon,
    type: 'collection',
    color: '#B91C1C',
    bg: '#FEF2F2',
    border: '#FECACA',
    region: 'China & Southeast Asia',
    stat: '3 hand-picked legs',
    sequenced: false,
    description:
      "Hainan Airlines works China's outbound short-haul the way a low-cost trunk carrier does — 737s from Beijing down to Bangkok and across to Tokyo, plus a southern-island hop from Haikou into Laos. A clean sample of how mainland China connects to its Southeast Asian neighbours.",
    legs: [
      { fn: 'HU429', from: 'Beijing', to: 'Bangkok', ac: 'Boeing 737-800', block: '04:45' },
      { fn: 'HU439', from: 'Beijing', to: 'Tokyo Narita', ac: 'Boeing 737-800', block: '03:10' },
      { fn: 'HU461', from: 'Haikou', to: 'Vientiane', ac: 'Boeing 737-800', block: '02:00', note: 'A tropical-island departure into Laos' },
    ],
  },
  {
    id: 'etihad-web',
    name: "Etihad's Abu Dhabi Web",
    tagline: 'Wider than the Gulf corridor already covered.',
    icon: FaBuilding,
    type: 'collection',
    color: '#0F766E',
    bg: '#F0FDFA',
    border: '#99F6E4',
    region: 'UAE · Global Hub',
    stat: '4 hand-picked legs',
    sequenced: false,
    description:
      "Etihad's spread reaches far past the obvious Gulf shuttle. Bengaluru and Ahmedabad on the Indian side, then a widebody east to Phuket and a Dreamliner across to Manila — a reminder of how much of Asia funnels through a single Abu Dhabi hub that the Golden Sands trail only begins to cover.",
    legs: [
      { fn: 'EY216', from: 'Abu Dhabi', to: 'Bengaluru', ac: 'Boeing 787-9', block: '03:55' },
      { fn: 'EY240', from: 'Abu Dhabi', to: 'Ahmedabad', ac: 'A321 / 787-9', block: '02:40' },
      { fn: 'EY430', from: 'Abu Dhabi', to: 'Phuket', ac: 'Boeing 777-300ER', block: '07:10', note: 'A widebody on a leisure run east' },
      { fn: 'EY440', from: 'Abu Dhabi', to: 'Manila', ac: 'Boeing 787-10', block: '09:15' },
    ],
  },
  {
    id: 'ryanair-chaos',
    name: 'The Ryanair Chaos Trail',
    tagline: 'Everything two hours, nothing on schedule.',
    icon: FaTag,
    type: 'collection',
    color: '#2563EB',
    bg: '#EFF6FF',
    border: '#BFDBFE',
    region: 'Europe · Low-Cost',
    stat: '3 hand-picked legs',
    sequenced: false,
    description:
      "The secondary-airport budget sprawl in three legs. Ryanair's 737 MAX fleet stitches together the routes the flag carriers ignore — Gran Canaria and Madrid up to Birmingham, Manchester down to Marrakesh. Point-to-point, quick layovers, and a schedule that lives or dies on the ground time.",
    legs: [
      { fn: 'FR1128', from: 'Gran Canaria', to: 'Birmingham', ac: 'Boeing 737 MAX', block: '04:00', note: 'Canary Islands sun run' },
      { fn: 'FR2084', from: 'Madrid', to: 'Birmingham', ac: 'Boeing 737 MAX', block: '02:00' },
      { fn: 'FR3126', from: 'Manchester', to: 'Marrakesh', ac: 'Boeing 737 MAX', block: '03:30', note: 'North Africa on a budget fare' },
    ],
  },
  {
    id: 'lot-long-reach',
    name: "LOT's Long Reach",
    tagline: 'A mid-size flag carrier punching above its weight.',
    icon: FaFeather,
    type: 'collection',
    color: '#4338CA',
    bg: '#EEF2FF',
    border: '#C7D2FE',
    region: 'Poland · Global',
    stat: '4 hand-picked legs',
    sequenced: false,
    description:
      "Warsaw is not the hub you'd expect to reach the Caribbean, and that's exactly the surprise. LOT works the Gulf and the Alps on 737s, then sends 787 Dreamliners clear across the Atlantic to Punta Cana and Cancún — a genuinely serious long-haul leisure network flown out of Central Europe.",
    legs: [
      { fn: 'LO121', from: 'Warsaw', to: 'Dubai', ac: 'Boeing 737 MAX', block: '05:00' },
      { fn: 'LO229', from: 'Warsaw', to: 'Innsbruck', ac: 'Boeing 737-800', block: '00:55', note: 'A ski-season alpine hop' },
      { fn: 'LO6305', from: 'Warsaw', to: 'Punta Cana', ac: 'Boeing 787-8', block: '10:30', note: 'A Dreamliner clear across the Atlantic' },
      { fn: 'LO6505', from: 'Warsaw', to: 'Cancún', ac: 'Boeing 787-8', block: '11:20' },
    ],
  },
  {
    id: 'egyptair-nile',
    name: "EgyptAir's Nile Network",
    tagline: 'The ancient-Egypt tourist circuit.',
    icon: FaMonument,
    type: 'collection',
    color: '#B45309',
    bg: '#FFFBEB',
    border: '#FDE68A',
    region: 'Egypt & the Nile',
    stat: '4 hand-picked legs',
    sequenced: false,
    description:
      "Cairo hub-and-spoke, straight down the tourist trail. EgyptAir's 737s run the short hops to the Red Sea resorts of Hurghada and Sharm El Sheikh and up the Nile to Luxor, then stretch across to Mumbai on the India feed. A whole country's worth of history strung between one-hour sectors.",
    legs: [
      { fn: 'MS46', from: 'Cairo', to: 'Hurghada', ac: 'Boeing 737-800', block: '01:00', note: 'Red Sea diving resort' },
      { fn: 'MS24', from: 'Cairo', to: 'Sharm El Sheikh', ac: 'Boeing 737-800', block: '01:00' },
      { fn: 'MS272', from: 'Cairo', to: 'Luxor', ac: 'Boeing 737-800', block: '01:05', note: 'Valley of the Kings, up the Nile' },
      { fn: 'MS968', from: 'Cairo', to: 'Mumbai', ac: 'Boeing 737-800', block: '05:25', note: 'The narrowbody India feed' },
    ],
  },
  {
    id: 'springbok-south',
    name: 'Springbok Deep South',
    tagline: 'South African Airways beyond the Baobab basics.',
    icon: FaHippo,
    type: 'collection',
    color: '#15803D',
    bg: '#F0FDF4',
    border: '#BBF7D0',
    region: 'Southern Africa · Long-Haul',
    stat: '4 hand-picked legs',
    sequenced: false,
    description:
      "The Baobab trail scratches the surface; this one goes deeper into South African Airways' own long-haul reach. Cape Town across to São Paulo, a rare direct Africa–Australia run to Perth, a short safari hop to Victoria Falls, and the marathon A340 haul from Johannesburg to New York. Big airframes, big distances, southern hemisphere throughout.",
    legs: [
      { fn: 'SA226', from: 'Cape Town', to: 'Sao Paulo', ac: 'A330-300', block: '08:55', note: 'A South Atlantic crossing' },
      { fn: 'SA280', from: 'Johannesburg', to: 'Perth', ac: 'A340-600', block: '09:25', note: 'A rare direct Africa–Australia link' },
      { fn: 'SA24', from: 'Johannesburg', to: 'Victoria Falls', ac: 'Boeing 737-800', block: '01:40', note: 'The safari hop to the falls' },
      { fn: 'SA203', from: 'Johannesburg', to: 'New York JFK', ac: 'A340-600', block: '16:15', note: 'One of the longest sectors on the network' },
    ],
  },
  {
    id: 'caribbean-circuit',
    name: 'The Caribbean Circuit',
    tagline: 'A full island network, not just one leg.',
    icon: FaSailboat,
    type: 'collection',
    color: '#0E7490',
    bg: '#ECFEFF',
    border: '#A5F3FC',
    region: 'Caribbean',
    stat: '5 hand-picked legs',
    sequenced: false,
    description:
      "Caribbean Airlines runs a proper island network — the big-city feeds from New York and Toronto into Kingston, the Kingston–St Maarten inter-island run, and a pair of tiny Dash 8 hops from Port of Spain out to Saint Lucia and St Vincent. Everything from a three-hour 737 leg to a fifty-minute turboprop island skip.",
    legs: [
      { fn: 'BW6', from: 'New York JFK', to: 'Kingston', ac: 'Boeing 737-800', block: '03:17', note: 'The North American feed' },
      { fn: 'BW78', from: 'Toronto', to: 'Kingston', ac: 'Boeing 737-800', block: '03:36' },
      { fn: 'BW457', from: 'Kingston', to: 'St Maarten', ac: 'Boeing 737-800 / MAX', block: '01:45', note: 'The famous Maho Beach approach' },
      { fn: 'BW434', from: 'Port of Spain', to: 'Saint Lucia', ac: 'Dash 8-Q400', block: '00:59', note: 'A turboprop island-hopper' },
      { fn: 'BW436', from: 'Port of Spain', to: 'St Vincent', ac: 'Dash 8-Q400', block: '00:48' },
    ],
  },

  // ── Cargo & Special Ops ─────────────────────────────────────────────────────
  {
    id: 'heavy-metal',
    name: 'The Heavy Metal Trail',
    tagline: 'Behind every passenger route, the metal that keeps it alive.',
    icon: FaBoxesPacking,
    type: 'cargo',
    color: '#334155',
    bg: '#F8FAFC',
    border: '#CBD5E1',
    region: 'Cargo & Regional Feeder Ops · Sequenced',
    stat: '2 sequenced cargo legs + 3 highlights',
    sequenced: true,
    description:
      "Not every mission carries passengers. This trail is INVA's operations sampler: a genuine two-leg freighter relay across Latin America on an MD-11F, a Saudia 777F hauling freight from Riyadh to Guangzhou, a Caribbean Dash 8 island-hopper, and a CRJ working the shortest kind of European feeder leg. Different checklists, different priorities, same professionalism required.",
    itinerary: [
      'Depart Guayaquil (SEGU) · VLO7432 (A) · block 5h30m (MD-11F)',
      'Arrive Mexico City · quick freighter layover, same airframe',
      'Depart Mexico City · VLO7432 (B) · block 3h30m (MD-11F) · arrive Los Angeles',
    ],
    legs: [
      { fn: 'VLO7432 (A)', from: 'Guayaquil', to: 'Mexico City', ac: 'MD-11F', block: '05:30' },
      { fn: 'VLO7432 (B)', from: 'Mexico City', to: 'Los Angeles', ac: 'MD-11F', block: '03:30' },
      { fn: 'SV978', from: 'Riyadh', to: 'Guangzhou', ac: 'Boeing 777F', block: '08:15', note: 'Suggested depart 02:00 local' },
      { fn: 'BW430', from: 'Port of Spain', to: 'Georgetown', ac: 'Dash 8-Q400', block: '00:31', note: 'Caribbean island-hopper' },
      { fn: 'LH390', from: 'Frankfurt', to: 'Luxembourg', ac: 'CRJ-900', block: '00:40', note: 'One of the shortest feeder legs on the network' },
    ],
  },
  {
    id: 'refuelling-stops',
    name: 'The Refuelling Stops',
    tagline: "Aviation's two most iconic gas-and-go airports, one trail.",
    icon: FaGasPump,
    type: 'cargo',
    color: '#475569',
    bg: '#F8FAFC',
    border: '#CBD5E1',
    region: 'North Atlantic & North Pacific',
    stat: '3 hand-picked legs',
    sequenced: false,
    description:
      "Before the twins could cross oceans nonstop, two airports made long-haul possible: Reykjavik on the North Atlantic and Anchorage on the North Pacific. This trail honours both — Icelandair's 757s working the Keflavík hub, and a Nippon Cargo 747-8 freighter making the classic polar fuel stop between Anchorage and Tokyo.",
    legs: [
      { fn: 'FI422', from: 'Reykjavik', to: 'Frankfurt', ac: 'Boeing 757-200 / 737 MAX', block: '03:40', note: 'The classic North Atlantic stopover hub' },
      { fn: 'FI453', from: 'Paris', to: 'Reykjavik', ac: 'Boeing 757-200 / 737 MAX', block: '03:40' },
      { fn: 'KZ131', from: 'Anchorage', to: 'Tokyo Narita', ac: 'Boeing 747-8F', block: '06:45', note: 'The North Pacific freighter gas-and-go' },
    ],
  },
  {
    id: 'qantaslink-outback',
    name: 'The QantasLink Outback Hopper',
    tagline: "Australia's domestic backbone, not its long-haul face.",
    icon: FaFeatherPointed,
    type: 'cargo',
    color: '#A16207',
    bg: '#FEFCE8',
    border: '#FDE68A',
    region: 'Australia · Regional Turboprop',
    stat: '2 hand-picked legs',
    sequenced: false,
    description:
      "The other side of Australian aviation. While the Southern Cross trail chases the long-haul giants, QantasLink's Dash 8-Q400s work the regional grind — Sydney out to Coffs Harbour, Brisbane down to Port Macquarie. Short turboprop sectors into small coastal fields, the quiet backbone that keeps the country connected.",
    legs: [
      { fn: 'QLK2106', from: 'Sydney', to: 'Coffs Harbour', ac: 'Dash 8-Q400', block: '01:15', note: 'A coastal regional hop' },
      { fn: 'QLK2171', from: 'Brisbane', to: 'Port Macquarie', ac: 'Dash 8-Q400', block: '01:20' },
    ],
  },
]
